"""Argument parser construction for the Warcraft Logs CLI."""
import argparse
from .models import GLOBAL_TOP_MAX, GLOBAL_MAX_PAGES
from .reports import _add_report_options, _add_json_report_options, EVENT_PAGE_LIMIT, EVENT_MAX_PAGES

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="warcraftlogs.py")
    parser.add_argument("--client-id")
    parser.add_argument("--client-secret")
    parser.add_argument("--env-file")
    parser.add_argument("--no-cache", action="store_true")
    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser("rate-limit")
    metadata = subparsers.add_parser("metadata")
    metadata.add_argument(
        "kind",
        choices=("regions", "realms", "zones", "encounters", "seasons", "classes", "specs", "affixes", "abilities"),
    )
    metadata.add_argument("--region")
    metadata.add_argument("--name")
    metadata.add_argument("--expansion-id", type=int)
    metadata.add_argument("--ability-limit", type=int, default=100)
    metadata.add_argument("--ability-page", type=int, default=1)
    report = subparsers.add_parser("report")
    report_parsers = report.add_subparsers(dest="report_command")
    summary = report_parsers.add_parser("summary")
    _add_report_options(summary)
    fights = report_parsers.add_parser("fights")
    _add_report_options(fights, window=True, translate=True)
    master_data = report_parsers.add_parser("master-data")
    _add_report_options(master_data, translate=True)
    player_details = report_parsers.add_parser("player-details")
    _add_json_report_options(player_details)
    player_details.add_argument("--no-translate", dest="translate", action="store_false", default=True)
    for kind in ("table", "graph"):
        command = report_parsers.add_parser(kind)
        _add_json_report_options(command)
        command.add_argument("--data-type", required=True)
        command.add_argument("--ability-id", type=float)
        command.add_argument("--death", type=int)
        command.add_argument("--filter-expression")
        command.add_argument("--source-auras-absent")
        command.add_argument("--source-auras-present")
        command.add_argument("--source-class")
        command.add_argument("--source-id", type=int)
        command.add_argument("--source-instance-id", type=int)
        command.add_argument("--source-pet-type")
        command.add_argument("--source-spec")
        command.add_argument("--target-auras-absent")
        command.add_argument("--target-auras-present")
        command.add_argument("--target-class")
        command.add_argument("--target-id", type=int)
        command.add_argument("--target-instance-id", type=int)
        command.add_argument("--target-pet-type")
        command.add_argument("--target-spec")
        command.add_argument("--hostility-type")
        command.add_argument("--view-by")
        command.add_argument("--wipe-cutoff", type=int)
        command.add_argument("--no-translate", dest="translate", action="store_false", default=True)
    events = report_parsers.add_parser("events")
    _add_report_options(events, window=True)
    events.add_argument("--data-type")
    events.add_argument("--source-id", type=int)
    events.add_argument("--target-id", type=int)
    events.add_argument("--ability-id", type=int)
    events.add_argument("--hostility")
    events.add_argument("--filter-expression")
    events.add_argument("--include-resources", action="store_true", default=None)
    events.add_argument("--use-actor-ids", action="store_true", default=None)
    events.add_argument("--use-ability-ids", action="store_true", default=None)
    events.add_argument("--event-limit", type=int, default=EVENT_PAGE_LIMIT)
    events.add_argument("--max-pages", type=int, default=EVENT_MAX_PAGES)
    events.add_argument("--output")
    rankings = report_parsers.add_parser("rankings")
    _add_report_options(rankings)
    rankings.add_argument("--difficulty", type=int)
    rankings.add_argument("--encounter-id", type=int)
    rankings.add_argument("--compare")
    rankings.add_argument("--player-metric")
    rankings.add_argument("--timeframe")
    find = subparsers.add_parser("find")
    find_parsers = find.add_subparsers(dest="find_command")

    def add_discovery_parser(command):
        command.add_argument("--name", required=True)
        command.add_argument("--server", required=True)
        command.add_argument("--region", required=True)
        command.add_argument("--page", type=int, default=1)
        command.add_argument("--limit", type=int, default=100)
        command.add_argument("--max-pages", type=int, default=1)
        command.add_argument("--class-name", "--class", dest="class_name")
        command.add_argument("--spec-name", "--spec", dest="spec_name")
        command.add_argument("--role")
        command.add_argument("--instance", type=int)
        command.add_argument("--zone", type=int)
        command.add_argument("--encounter", "--encounter-id", dest="encounter", type=int)
        command.add_argument("--season", type=int)
        command.add_argument("--partition", type=int)
        command.add_argument("--key-min", type=int)
        command.add_argument("--key-max", type=int)
        command.add_argument("--affixes", "--affix", dest="affixes", action="append")
        command.add_argument("--timed", action="store_true", default=None)
        command.add_argument("--depleted", action="store_true", default=None)
        command.add_argument("--difficulty", type=int)
        command.add_argument("--kill", action="store_true", default=None)
        command.add_argument("--wipe", action="store_true", default=None)
        command.add_argument("--start-time", type=float)
        command.add_argument("--end-time", type=float)

    add_discovery_parser(find_parsers.add_parser("character"))
    add_discovery_parser(find_parsers.add_parser("guild"))
    global_find = find_parsers.add_parser("global")
    global_scope = global_find.add_mutually_exclusive_group(required=True)
    global_scope.add_argument("--zone")
    global_scope.add_argument("--instance")
    global_scope.add_argument("--encounter", "--encounter-id", dest="encounter")
    global_find.add_argument("--expansion-id", type=int)
    global_find.add_argument("--page", type=int, default=1)
    global_find.add_argument("--top", type=int, default=100)
    global_find.add_argument("--max-pages", type=int, default=1)
    global_find.add_argument("--class-name", "--class", dest="class_name")
    global_find.add_argument("--spec-name", "--spec", dest="spec_name")
    global_find.add_argument("--role")
    global_find.add_argument("--partition")
    global_find.add_argument("--difficulty")
    global_find.add_argument("--key-min", type=int)
    global_find.add_argument("--key-max", type=int)
    global_find.add_argument("--affixes", "--affix", dest="affixes", action="append")
    global_find.add_argument("--timed", action="store_true", default=None)
    global_find.add_argument("--depleted", action="store_true", default=None)
    global_find.add_argument("--kill", action="store_true", default=None)
    global_find.add_argument("--wipe", action="store_true", default=None)
    global_find.add_argument("--start-time", type=float)
    global_find.add_argument("--end-time", type=float)
    global_find.add_argument("--metric")
    global_find.add_argument("--leaderboard")
    global_find.add_argument("--server-region")
    global_find.add_argument("--server-slug")
    return parser


