query EncounterRankings($encounterID: Int!, $zoneID: Int!, $difficulty: Int, $partition: Int, $page: Int, $serverRegion: String, $metric: FightRankingMetricType, $bracket: Int, $filter: String, $size: Int, $includeOtherPlayers: Boolean) {
  worldData {
    zone(id: $zoneID) {
      id
      encounters { id name }
    }
    encounter(id: $encounterID) {
      fightRankings(bracket: $bracket, difficulty: $difficulty, filter: $filter, page: $page, partition: $partition, serverRegion: $serverRegion, size: $size, metric: $metric, includeOtherPlayers: $includeOtherPlayers)
    }
  }
}
