query ReportGraph($code: String!, $allowUnlisted: Boolean!, $dataType: GraphDataType, $abilityID: Float, $death: Int, $difficulty: Int, $encounterID: Int, $endTime: Float, $fightIDs: [Int], $filterExpression: String, $hostilityType: HostilityType, $killType: KillType, $sourceAurasAbsent: String, $sourceAurasPresent: String, $sourceClass: String, $sourceID: Int, $sourceInstanceID: Int, $startTime: Float, $targetAurasAbsent: String, $targetAurasPresent: String, $targetClass: String, $targetID: Int, $translate: Boolean, $viewOptions: Int, $viewBy: ViewType, $wipeCutoff: Int) {
  reportData {
    report(code: $code, allowUnlisted: $allowUnlisted) {
      visibility
      archiveStatus { isArchived isAccessible archiveDate }
      graph(dataType: $dataType, abilityID: $abilityID, death: $death, difficulty: $difficulty, encounterID: $encounterID, endTime: $endTime, fightIDs: $fightIDs, filterExpression: $filterExpression, hostilityType: $hostilityType, killType: $killType, sourceAurasAbsent: $sourceAurasAbsent, sourceAurasPresent: $sourceAurasPresent, sourceClass: $sourceClass, sourceID: $sourceID, sourceInstanceID: $sourceInstanceID, startTime: $startTime, targetAurasAbsent: $targetAurasAbsent, targetAurasPresent: $targetAurasPresent, targetClass: $targetClass, targetID: $targetID, translate: $translate, viewOptions: $viewOptions, viewBy: $viewBy, wipeCutoff: $wipeCutoff)
    }
  }
}
