query ReportPlayerDetails($code: String!, $allowUnlisted: Boolean!, $difficulty: Int, $encounterID: Int, $endTime: Float, $fightIDs: [Int], $killType: KillType, $startTime: Float, $translate: Boolean) {
  reportData {
    report(code: $code, allowUnlisted: $allowUnlisted) {
      visibility
      archiveStatus { isArchived isAccessible archiveDate }
      playerDetails(difficulty: $difficulty, encounterID: $encounterID, endTime: $endTime, fightIDs: $fightIDs, includeCombatantInfo: true, killType: $killType, startTime: $startTime, translate: $translate)
    }
  }
}
